=pod

=head1 PREREQUISITES

For generating an OCSP staple you will need to following:

=head2 OpenSSL

OpenSSL with ocsp application installed

=head2 Certificates

=over

=item *

Server certificate (server.crt)

=item *

Issuer certificate (issuer.crt)

=item *

Full Certificate Authority chain (full-CA.crt) - this includes the issuer certificate, any number of intermediate certificate and ends with the root certificate

=back

=head1 GETING AN OCSP STAPLE

=head2 Get the OCSP responder URI

    openssl x509 -noout -ocsp_uri -in server.crt

=head2 Query the OCSP responder

    openssl ocsp -no_nonce -issuer -cert server.crt issuer.crt -CAfile full-CA.crt -url OCSP_responder_URI -header "HOST" OCSP_response_host -respout /path/to/OCSP_staple.der

=head2 Inspecting an OCSP staple

    openssl ocsp -respin /path/to/OCSP_staple.der -text -CAfile full-CA.crt

=head1 USAGE

=head2 Set an OCSP staple to be used within a SSL session

    $ocsp_index = $ssl->set_OCSP_staple( $ocsp_index, '/path/to/OCSP_staple.der' );

=head2 Refreshing an already allocated OCSP staple buffer

    Crypt::MatrixSSL3::refresh_OCSP_staple( undef, $ocsp_index, '/path/to/OCSP_staple.der' );

=cut
